// Leaflet Map
export const MAP_Y = 5656;
export const MAP_X = 8000;

// Tile pyramid for the main map, generated by scripts/generate-tiles.mjs. The
// levels are cut from the master image resized into the MAP_X / MAP_Y bounds,
// so changing those bounds means regenerating the tiles.
export const TILE_URL = '/tiles/{z}/{x}/{y}.webp';
export const TILE_SIZE = 256;
export const TILE_MIN_ZOOM = -6;
export const TILE_MAX_ZOOM = 0;
// Every zoom level on this map is negative, which makes for awkward directory
// names, so tile paths are offset to keep them positive
export const TILE_ZOOM_OFFSET = 6;

export const BASE_URL = 'https://fdn17wuw0h.execute-api.eu-west-1.amazonaws.com/dev/api/v1';